name: Deploy
on:
  repository_dispatch:
    types: [rebuild]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: yarn install
    - run: yarn build
    - run: yarn deploy
